server:
  # undertow
  undertow:
    accesslog:
      dir: ./log/ # Undertow access log directory.
      enabled: false # Enable access log.
      pattern: '%t [%I] %a %r %s (%b Byte) (%T ms)' # Format pattern for access logs.
      prefix: access_log. # Log file name prefix.
      rotate: true # Enable access log rotation.
      suffix: log # Log file name suffix.
    buffer-size: # Size of each buffer in bytes.
    buffers-per-region: # Number of buffer per region.
    direct-buffers: # Allocate buffers outside the Java heap.
    io-threads: # Number of I/O threads to create for the worker.
    max-http-post-size: 0 # Maximum size in bytes of the HTTP post content.
    worker-threads: # Number of worker threads.
  port: 8011
  servlet:
    context-path: /

spring:
  application:
    name: eureka-client-8001
  # 环境设置 dev|test|prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka #单个服务注册中心
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #集群服务注册中心
  instance:
    instance-id: hystrix-8011 #可以给本服务起别名
    prefer-ip-address: true #访问路径可以显示ip地址

info:
  app.name: SpringCloudDemo~~~hystrix-8011
  company.name: zsk
  bulid.artifactId: $project.artifactId$
  bulid.version: $project.version$